//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTMTool.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.TicketsAccessHistory = new HashSet<TicketsAccessHistory>();
            this.TicketsMessagesHistory = new HashSet<TicketsMessagesHistory>();
            this.TicketsStatusHistory = new HashSet<TicketsStatusHistory>();
        }
    
        public int IdTicket { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string User { get; set; }
        public int IdType { get; set; }
        public string AppCode { get; set; }
        public int IdSection { get; set; }
        public string AppVersion { get; set; }
        public string SourceIdentification { get; set; }
        public Nullable<int> PriorityLevel { get; set; }
        public Nullable<int> PriorityAsignedTo { get; set; }
        public Nullable<int> AsignedTo { get; set; }
        public string Comment { get; set; }
        public string ImageFile1 { get; set; }
        public string ImageFile2 { get; set; }
        public string ImageFile3 { get; set; }
        public string ImageFile4 { get; set; }
        public string Subject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketsAccessHistory> TicketsAccessHistory { get; set; }
        public virtual TicketsExceptionInfo TicketsExceptionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketsMessagesHistory> TicketsMessagesHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketsStatusHistory> TicketsStatusHistory { get; set; }
    }
}
