//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTMTool.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VLTMModelConnection : DbContext
    {
        public VLTMModelConnection()
            : base("name=VLTMModelConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<temp_vTechnicalUsers> temp_vTechnicalUsers { get; set; }
        public virtual DbSet<TicketsAccessHistory> TicketsAccessHistory { get; set; }
        public virtual DbSet<TicketsExceptionInfo> TicketsExceptionInfo { get; set; }
        public virtual DbSet<TicketsMessagesHistory> TicketsMessagesHistory { get; set; }
        public virtual DbSet<TicketsStatusHistory> TicketsStatusHistory { get; set; }
        public virtual DbSet<TicketStatus> TicketStatus { get; set; }
        public virtual DbSet<TicketTypes> TicketTypes { get; set; }
        public virtual DbSet<vTickets> vTickets { get; set; }
        public virtual DbSet<vTicketsStatusHistory> vTicketsStatusHistory { get; set; }
        public virtual DbSet<vTHORApplications> vTHORApplications { get; set; }
        public virtual DbSet<vTHOREmployes> vTHOREmployes { get; set; }
        public virtual DbSet<vTHORApplicationSections> vTHORApplicationSections { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    }
}
