//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTMTool.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTHOREmployes
    {
        public string EmployeeCode { get; set; }
        public int EmployeeNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Department { get; set; }
        public string Subdepartment { get; set; }
        public string Email { get; set; }
        public Nullable<bool> AllowImputation { get; set; }
        public string HolidaysCalendar { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
