//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTMTool.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTHORApplicationSections
    {
        public string AppCode { get; set; }
        public int IdSection { get; set; }
        public string AppSectionName { get; set; }
        public string AppSectionDescription { get; set; }
    }
}
